version: '3'

services:
   backend_application:
      container_name: backend_application
      image: node:14
      volumes:
         - './server'
      tty: true
      ports:
         - 3000:3000
      environment:
         ENV: dev
         MYSQL_PASSWORD: ${MYSQL_PASSWORD}
         MYSQL_DB: ${MYSQL_DB}
         MYSQL_USER: ${MYSQL_USER}
         MYSQL_HOST: mysql_application
      command: >
         npm install 
         && npm run dev

   mysql_application:
      container_name: mysql_application
      image: mysql:8.0
      ports:
         - 127.0.0.1:3306:3306
      environment:
         MYSQL_PASSWORD: ${MYSQL_PASSWORD}
         MYSQL_DB: ${MYSQL_DB}
         MYSQL_USER: ${MYSQL_USER}
         MYSQL_HOST: '%'
      tty: true
